# Add 'train-gds-booking' to any changes within 'example' folder or any subfolders
label_test:
  - changed-files: src/**

label2:
  - changed-files: e2e/**

label_branch_name:
  - head-branch: '^fix'

